### ISSUE TITLE
No javadoc and sources avaliable for 2.7.1

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/plexus-io#4]
Hi,

It looks like the Javadoc and source artifacts are not available from the Maven repo for plexus-io 2.7.1.

**Comment by michael-o** [comment]
Is this still required?

**Comment by plamentotev** [comment]
As you can see there are no Javadoc and source artifacts for plexus-io 2.7.1 (http://central.maven.org/maven2/org/codehaus/plexus/plexus-io/2.7.1/), while for the previous versions there are (http://central.maven.org/maven2/org/codehaus/plexus/plexus-io/2.7/). It's not something important, especially given the fact that 3.0.0 is going to be released soon.

**Comment by michael-o** [comment]
I do not even understand how this passed oss.sonatype.org checks.

**Comment by michael-o** [comment]
2.7.1 is generally broken if you take a closer look. No file is GPG signed. I will do the following now. I will branch off before Java 7, and release 2.7.2. It that OK for you?

**Comment by plamentotev** [comment]
Yes. Thanks.

**Comment by michael-o** [comment]
It pretty much looks like Plexus IO is unreleasable on Windows:

    Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.087 sec <<< FAILURE!
    testSrcResource(org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtilsTest)  Time elapsed: 10 sec  <<< ERROR!
    java.io.IOException: Failed to quote directory: 'src\test\resources\symlinks':Error while executing process.
    
    Executing: cmd.exe /X /C "ls -1nlaR D:\Entwicklung\Projekte\plexus-io\src\test\resources\symlinks"
    
    
            at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPathScreenScrape(PlexusIoResourceAttributeUtils.java:258)
            at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtilsTest.testSrcResource(PlexusIoResourceAttributeUtilsTest.java:192)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at junit.framework.TestCase.runTest(TestCase.java:176)
            at junit.framework.TestCase.runBare(TestCase.java:141)
            at junit.framework.TestResult$1.protect(TestResult.java:122)
            at junit.framework.TestResult.runProtected(TestResult.java:142)
            at junit.framework.TestResult.run(TestResult.java:125)
            at junit.framework.TestCase.run(TestCase.java:129)
            at junit.framework.TestSuite.runTest(TestSuite.java:252)
            at junit.framework.TestSuite.run(TestSuite.java:247)
            at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
            at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
            at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
            at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
            at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
            at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
            at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:80)
            at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:724)
            at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAllProviders(AbstractSurefireMojo.java:682)
            at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:648)
            at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:586)
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
            at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
            at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
            at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
            at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
            at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
            at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
            at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
            at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
            at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error while executing process.
            at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:675)
            at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLineAsCallable(CommandLineUtils.java:134)
            at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPathScreenScrape(PlexusIoResourceAttributeUtils.java:250)
            ... 51 more
    Caused by: java.io.IOException: Cannot run program "ls": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
            at java.lang.Runtime.exec(Runtime.java:620)
            at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:655)
            ... 53 more
    Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
            at java.lang.ProcessImpl.create(Native Method)
            at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
            at java.lang.ProcessImpl.start(ProcessImpl.java:137)
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
            ... 55 more

**Comment by michael-o** [comment]
Artifacts on their way.

**Comment by michael-o** [comment]
2.7.2 is on central and supersedes 2.7.1. Issue solved.
